# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:

  resq:
  
    runs-on: ubuntu-latest

    steps:
      - name: 'build'
        run: echo "hola tonotos"
   
